server:
  port: 8081

spring:
  application:
    name: order-service
  jackson:
    serialization:
      write-dates-as-timestamps: false

  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    root: WARN
    org.flywaydb: DEBUG
    org.apache.kafka: ERROR
    kafka: ERROR
    org.springframework.kafka: ERROR

security:
  jwt:
    secret: very-secret-key-change-this-in-prod-1234567890
    expiration: 3600000

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    auto-startup: true
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "com.akhil.orders.event"
      spring.json.value.default.type: com.akhil.orders.event.OrderCreatedEvent
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.trusted.packages: "com.akhil.orders.event"
      spring.json.value.default.type: com.akhil.orders.event.OrderCreatedEvent


